# Generated by Django 3.1.2 on 2021-04-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.PositiveSmallIntegerField(max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('value', models.FloatField(max_length=10)),
                ('measurement_unit', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
