# Generated by Django 3.1.2 on 2021-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='s_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
