# Generated by Django 3.1.2 on 2021-04-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherbox', '0002_auto_20210409_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.FloatField(),
        ),
    ]
