# Generated by Django 3.1.2 on 2021-05-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherbox', '0003_changed_field_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='measurement_unit',
        ),
    ]
