# Generated by Django 3.1.2 on 2021-05-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherbox', '0004_remove_data_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='s_id',
        ),
    ]
